<?php

function register_cpt_success_stories() {
	$labels = [
		"name" => __( "Success Stories", "custom-post-type-ui" ),
		"singular_name" => __( "Success Story", "custom-post-type-ui" ),
		"menu_name" => __( "Success Stories", "custom-post-type-ui" ),
		"all_items" => __( "All Success Stories", "custom-post-type-ui" ),
		"add_new" => __( "Add New", "custom-post-type-ui" ),
		"add_new_item" => __( "Add New Success Story", "custom-post-type-ui" ),
		"edit_item" => __( "Edit Success Story", "custom-post-type-ui" ),
		"new_item" => __( "New Success Story", "custom-post-type-ui" ),
		"view_item" => __( "View Success Story", "custom-post-type-ui" ),
		"view_items" => __( "View Success Stories", "custom-post-type-ui" ),
		"search_items" => __( "Search Success Stories", "custom-post-type-ui" ),
		"not_found" => __( "No Success Stories found", "custom-post-type-ui" ),
		"not_found_in_trash" => __( "No Success Stories found in Trash", "custom-post-type-ui" ),
		"parent" => __( "Parent Success Story:", "custom-post-type-ui" ),
		"featured_image" => __( "Featured image", "custom-post-type-ui" ),
		"set_featured_image" => __( "Set featured image", "custom-post-type-ui" ),
		"remove_featured_image" => __( "Remove featured image", "custom-post-type-ui" ),
		"use_featured_image" => __( "Use as featured image", "custom-post-type-ui" ),
		"archives" => __( "Success Story archives", "custom-post-type-ui" ),
		"insert_into_item" => __( "Insert into Success Story", "custom-post-type-ui" ),
		"uploaded_to_this_item" => __( "Uploaded to this Success Story", "custom-post-type-ui" ),
		"filter_items_list" => __( "Filter Success Stories list", "custom-post-type-ui" ),
		"items_list_navigation" => __( "Success Stories list navigation", "custom-post-type-ui" ),
		"items_list" => __( "Success Stories list", "custom-post-type-ui" ),
		"attributes" => __( "Success Stories Attributes", "custom-post-type-ui" ),
		"name_admin_bar" => __( "Success Story", "custom-post-type-ui" ),
		"item_published" => __( "Success Story published", "custom-post-type-ui" ),
		"item_published_privately" => __( "Success Story published privately", "custom-post-type-ui" ),
		"item_reverted_to_draft" => __( "Success Story reverted to draft", "custom-post-type-ui" ),
		"item_scheduled" => __( "Success Story scheduled", "custom-post-type-ui" ),
		"item_updated" => __( "Success Story updated", "custom-post-type-ui" ),
		"parent_item_colon" => __( "Parent Success Story:", "custom-post-type-ui" ),
	];

	$args = [
		"label" => __( "Success Stories", "custom-post-type-ui" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => false,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => [ "slug" => "success_stories", "with_front" => false ],
		"query_var" => true,
		"menu_position" => 25,
		"menu_icon" => "dashicons-universal-access",
		"supports" => [ "title", "thumbnail", "custom-fields" ],
	];

	register_post_type( "success_stories", $args );
}
add_action( 'init', 'register_cpt_success_stories' );